version: '3.8'
services:
  graphql-engine:
    image: hasura/graphql-engine:v2.37.1
    ports:
      - "8080:8080"
    restart: always
    environment:
      # postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres.sycpmqwjdcbdbsoqowaj:marqu7-tyhvob-Wydnab@aws-0-us-west-1.pooler.supabase.com:6543/postgres
      # this env var can be used to add the above postgres database to Hasura as a data source
      PG_DATABASE_URL: postgres://postgres.sycpmqwjdcbdbsoqowaj:marqu7-tyhvob-Wydnab@aws-0-us-west-1.pooler.supabase.com:6543/postgres
      # enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      # enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      # uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key": "secret-for-testing-locally-with-emulator"}'